### ISSUE TITLE
httpService.create is not a function

### ISSUE THREAD

**Issue by dutzi** [austinkelleher/giphy-api#52]
Hi guys,

After upgrading to 1.2.8 we get the following error:

`httpService.create is not a function`

**Comment by austinkelleher** [comment]
@dutzi Thanks again for quickly reporting this issue. I fixed this issue in both 2.0 and backported the change to 1.0. Published `giphy-api@2.0.1` and `giphy-api@1.2.9` with the fix.
